"""remove info from lead

Revision ID: 661df9c7a770
Revises: 912e35cad2e0
Create Date: 2025-07-19 21:52:10.501943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '661df9c7a770'
down_revision: Union[str, None] = '912e35cad2e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leads', 'info')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('info', sqlite.JSON(), nullable=False))
    # ### end Alembic commands ###
